"""Create all 24 tables matching mockData.ts

Revision ID: 9ce4e1df3955
Revises: 
Create Date: 2026-10-01 14:34:08.150164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce4e1df3955'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('linked_entity_type', sa.String(), nullable=True),
    sa.Column('linked_entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('leads_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('config_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_config_config_type'), 'marketing_config', ['config_type'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('leads_count', sa.Integer(), nullable=True),
    sa.Column('requirements_count', sa.Integer(), nullable=True),
    sa.Column('opportunities_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_partners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('short_loc', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('availability_date', sa.String(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('last_verified_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_category'), 'properties', ['category'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_index(op.f('ix_properties_short_loc'), 'properties', ['short_loc'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('party_id', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=True),
    sa.Column('ai_trail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('call_recordings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('party_id', sa.String(), nullable=True),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.Column('party_phone', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_formatted', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('rates', sa.JSON(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(), nullable=False),
    sa.Column('uploaded_by_name', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.Column('party_id', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('call_type', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('caller_name', sa.String(), nullable=True),
    sa.Column('caller_id', sa.String(), nullable=True),
    sa.Column('call_time', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('callback_time', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('ai_transcript', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_rates', sa.JSON(), nullable=True),
    sa.Column('ai_sentiment', sa.String(), nullable=True),
    sa.Column('ai_next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_caller_id'), 'calls', ['caller_id'], unique=False)
    op.create_index(op.f('ix_calls_party_id'), 'calls', ['party_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('transaction_types', sa.JSON(), nullable=True),
    sa.Column('planned_budget', sa.Float(), nullable=True),
    sa.Column('actual_spend', sa.Float(), nullable=True),
    sa.Column('target_leads', sa.Integer(), nullable=True),
    sa.Column('target_qualified_leads', sa.Integer(), nullable=True),
    sa.Column('target_opportunities', sa.Integer(), nullable=True),
    sa.Column('promoted_properties', sa.JSON(), nullable=True),
    sa.Column('participating_partner_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_owner_id'), 'campaigns', ['owner_id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('linked_campaign_ids', sa.JSON(), nullable=True),
    sa.Column('linked_property_id', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('date_added', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['linked_property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('today_visit_count', sa.Integer(), nullable=True),
    sa.Column('week_completed_visits', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('last_known_location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('responsible_name', sa.String(), nullable=True),
    sa.Column('responsible_id', sa.String(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_client_id'), 'follow_ups', ['client_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_responsible_id'), 'follow_ups', ['responsible_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('assigned_to_id', sa.String(), nullable=True),
    sa.Column('assigned_to_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('preferred_short_locs', sa.JSON(), nullable=True),
    sa.Column('alternate_locs', sa.JSON(), nullable=True),
    sa.Column('min_budget', sa.Float(), nullable=True),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.Column('min_area', sa.Float(), nullable=True),
    sa.Column('max_area', sa.Float(), nullable=True),
    sa.Column('timeline', sa.String(), nullable=True),
    sa.Column('facilities', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_assigned_to_id'), 'requirements', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_requirements_client_id'), 'requirements', ['client_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('assigned_to_name', sa.String(), nullable=True),
    sa.Column('assigned_to_id', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('linked_record_type', sa.String(), nullable=True),
    sa.Column('linked_record_id', sa.String(), nullable=True),
    sa.Column('linked_record_label', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('property_short_loc', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.String(), nullable=False),
    sa.Column('submitted_date', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('checklist_template', sa.String(), nullable=True),
    sa.Column('review_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_agent_id'), 'visits', ['agent_id'], unique=False)
    op.create_index(op.f('ix_visits_client_id'), 'visits', ['client_id'], unique=False)
    op.create_index(op.f('ix_visits_property_id'), 'visits', ['property_id'], unique=False)
    op.create_table('campaign_promotions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('marketing_headline', sa.String(), nullable=True),
    sa.Column('marketing_description', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('media_attachments', sa.JSON(), nullable=True),
    sa.Column('enquiries_count', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_promotions_campaign_id'), 'campaign_promotions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_promotions_property_id'), 'campaign_promotions', ['property_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('party_id', sa.String(), nullable=False),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.Column('channel_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('lead_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('assigned_to_id', sa.String(), nullable=True),
    sa.Column('assigned_to_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('last_activity_at', sa.String(), nullable=True),
    sa.Column('next_follow_up_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('ad_reference', sa.String(), nullable=True),
    sa.Column('enquiry_at', sa.String(), nullable=True),
    sa.Column('referral_partner_id', sa.String(), nullable=True),
    sa.Column('referral_partner_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['referral_partner_id'], ['referral_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_to_id'), 'leads', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_party_id'), 'leads', ['party_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requirement_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('match_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_property_id'), 'matches', ['property_id'], unique=False)
    op.create_index(op.f('ix_matches_requirement_id'), 'matches', ['requirement_id'], unique=False)
    op.create_table('telemarketing_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('linked_campaign_id', sa.String(), nullable=True),
    sa.Column('linked_campaign_name', sa.String(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('assigned_telecallers', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['linked_campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('property_short_loc', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('lost_reason', sa.String(), nullable=True),
    sa.Column('lost_remarks', sa.Text(), nullable=True),
    sa.Column('negotiation_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('closed_at', sa.String(), nullable=True),
    sa.Column('originating_lead_id', sa.String(), nullable=True),
    sa.Column('attributed_campaign_id', sa.String(), nullable=True),
    sa.Column('attributed_campaign_name', sa.String(), nullable=True),
    sa.Column('attributed_channel_type', sa.String(), nullable=True),
    sa.Column('attributed_source', sa.String(), nullable=True),
    sa.Column('marketing_executive_name', sa.String(), nullable=True),
    sa.Column('first_touch_source', sa.String(), nullable=True),
    sa.Column('latest_touch_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attributed_campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['originating_lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_agent_id'), 'opportunities', ['agent_id'], unique=False)
    op.create_index(op.f('ix_opportunities_client_id'), 'opportunities', ['client_id'], unique=False)
    op.create_index(op.f('ix_opportunities_property_id'), 'opportunities', ['property_id'], unique=False)
    op.create_table('telemarketing_contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('party_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_attempt_at', sa.String(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('assigned_telecaller', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.String(), nullable=True),
    sa.Column('converted_lead_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['telemarketing_campaigns.id'], ),
    sa.ForeignKeyConstraint(['converted_lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemarketing_contacts_campaign_id'), 'telemarketing_contacts', ['campaign_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('property_short_loc', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('staff_id', sa.String(), nullable=True),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('staff_role', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_value', sa.Float(), nullable=False),
    sa.Column('commission_pct', sa.Float(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('closed_date', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('originating_lead_id', sa.String(), nullable=True),
    sa.Column('attributed_campaign_id', sa.String(), nullable=True),
    sa.Column('attributed_campaign_name', sa.String(), nullable=True),
    sa.Column('attributed_channel_type', sa.String(), nullable=True),
    sa.Column('attributed_source', sa.String(), nullable=True),
    sa.Column('marketing_executive_name', sa.String(), nullable=True),
    sa.Column('first_touch_source', sa.String(), nullable=True),
    sa.Column('latest_touch_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attributed_campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['originating_lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_opportunity_id'), 'transactions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_transactions_property_id'), 'transactions', ['property_id'], unique=False)
    op.create_index(op.f('ix_transactions_staff_id'), 'transactions', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_staff_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_property_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_opportunity_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_telemarketing_contacts_campaign_id'), table_name='telemarketing_contacts')
    op.drop_table('telemarketing_contacts')
    op.drop_index(op.f('ix_opportunities_property_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_client_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_agent_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('telemarketing_campaigns')
    op.drop_index(op.f('ix_matches_requirement_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_property_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_leads_party_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_campaign_promotions_property_id'), table_name='campaign_promotions')
    op.drop_index(op.f('ix_campaign_promotions_campaign_id'), table_name='campaign_promotions')
    op.drop_table('campaign_promotions')
    op.drop_index(op.f('ix_visits_property_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_client_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_agent_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_requirements_client_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_assigned_to_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_follow_ups_responsible_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_client_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_table('field_agents')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_campaigns_owner_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_calls_party_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_caller_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_table('call_recordings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_short_loc'), table_name='properties')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_category'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('referral_partners')
    op.drop_table('parties')
    op.drop_index(op.f('ix_marketing_config_config_type'), table_name='marketing_config')
    op.drop_table('marketing_config')
    op.drop_table('lead_sources')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
